### ISSUE TITLE
Get an error when trying to run the script

### ISSUE THREAD

**Issue by Alexande-rChan** [zhoujingchun03/PDRMRV#1]
main.m
```
img = (imread('001.jpg'));
out = mytest(img,1);
imwrite(out,imwrite_store1);
```
Error message
```
>> main
"Fig:1 å¼€å§‹
""Fig:1 redCompensate ç»“æŸ
"Undefined function or variable 'illuminationAdj'.

Error in mytest

Error in main (line 2)
out = mytest(img,1);
```

**Comment by xingyumex** [comment]
How can I fix this issue? I'm experiencing the same problem:

>> main
"Fig:1 å¼€å§‹
""Fig:1 redCompensate ç»“æ�Ÿ
"Undefined function or variable 'illuminationAdj'.

Error in mytest

Error in main (line 2)
out = mytest(img,1);

**Comment by mickoluan** [comment]
> How can I fix this issue? I'm experiencing the same problem:
> 
> > > main
> > > "Fig:1 å¼€å§‹
> > > ""Fig:1 redCompensate ç»“æ�Ÿ
> > > "Undefined function or variable 'illuminationAdj'.
> 
> Error in mytest
> 请问解决了吗？遇到了相同的问题

> Error in main (line 2) out = mytest(img,1);

**Comment by mickoluan** [comment]
> How can I fix this issue? I'm experiencing the same problem:
> 
> > > main
> > > "Fig:1 å¼€å§‹
> > > ""Fig:1 redCompensate ç»“æ�Ÿ
> > > "Undefined function or variable 'illuminationAdj'.
> 
> Error in mytest
> 
> Error in main (line 2) out = mytest(img,1);

请问解决了吗？遇到了相同的问题
